#model configuration
model_name: "transformer"
vocab_size: 10000
num_layers: 4
num_heads: 16
d_model: 512
d_ff: 1344
context_length: 256
theta: 10000

# data loading
train_dataset_path: "data/training_data/tiny_train.npy"
val_dataset_path: "data/training_data/tiny_valid.npy"
tokenizer_vocab_path: "data/tokenizer_data/vocab_tiny.pkl"
tokenizer_merges_path: "data/tokenizer_data/merges_tiny.pkl"

# Training configuration
dtype: float32 # bfloat16
batch_size: 2
min_learning_rate: 0.001
max_learning_rate: 0.01
weight_decay: 0.01
warmup_steps: 10
total_steps: 1001
cosine_cycle_steps: 900
betas: [0.9, 0.999]
eps: 1.0e-8
muon_momemtum: 0.95
grad_clip_norm: 1.0
optimizer: "adamw"
scheduler: "cosine"

# Experiment configuration
experiment_name: "base_cpu"
seed: 42
log_interval: 100
eval_interval: 500
save_interval: 1000
output_dir: "cs336_basics/configs/experiments"
wandb_project: "lm_training"
from_checkpoint: null #"cs336_basics/checkpoints/baseline_2000.pth"