#model configuration
model_name: "transformer"
vocab_size: 10000
num_layers: 4
num_heads: 16
d_model: 512
d_ff: 2048
context_length: 256
theta: 10000
pre_norm: true
layer_norm: true
glu: true

# data loading
train_dataset_path: "data/training_data/tiny_train.npy"
val_dataset_path: "data/training_data/tiny_valid.npy"
tokenizer_vocab_path: "data/tokenizer_data/vocab_tiny.pkl"
tokenizer_merges_path: "data/tokenizer_data/merges_tiny.pkl"

# Training configuration
dtype: float32 # bfloat16
batch_size: 128
min_learning_rate: 1.0e-5
max_learning_rate: 0.005
weight_decay: 0.1
warmup_steps: 400
total_steps: 5001
cosine_cycle_steps: 5001
betas: [0.9, 0.95]
eps: 1.0e-8
muon_momentum: 0.95
grad_clip_norm: 1.0
optimizer: "adamw"
scheduler: "cosine"

# Experiment configuration
experiment_name: "step_law_lr_low_batch_size"
seed: 42
log_interval: 10
eval_interval: 100
save_interval: 5000
output_dir: "cs336_basics/configs/experiments"
wandb_project: H100-testruns
from_checkpoint: null #"cs336_basics/checkpoints/baseline_2000.pth"