_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 2
betas:
    value:
        - 0.9
        - 0.999
context_length:
    value: 256
cosine_cycle_steps:
    value: 900
d_ff:
    value: 48
d_model:
    value: 12
dtype:
    value: float32
eps:
    value: 1e-08
eval_interval:
    value: 500
experiment_name:
    value: wandb_test
from_checkpoint:
    value: null
grad_clip_norm:
    value: 1
log_interval:
    value: 10
max_learning_rate:
    value: 0.01
min_learning_rate:
    value: 0.001
model_name:
    value: transformer
num_heads:
    value: 2
num_layers:
    value: 6
optimizer:
    value: adamw
output_dir:
    value: cs336_basics/configs/experiments
save_interval:
    value: 1000
scheduler:
    value: cosine
seed:
    value: 42
theta:
    value: 1000
total_steps:
    value: 2001
train_dataset_path:
    value: data/test_array2.npy
val_dataset_path:
    value: data/test_array.npy
vocab_size:
    value: 10000
wandb_project:
    value: test_logging
warmup_steps:
    value: 10
weight_decay:
    value: 0.01
